apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.name}}
  labels:
    app: {{ .Values.services.label}}
spec:
  ports:
  - port: {{ .Values.services.port}}
    targetPort: {{ .Values.services.targetPort}}
    protocol: TCP
  # Note here that we match both the app and the version
  selector:
    app: {{ .Values.services.label}}